<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>Unified UI Avalonia</AssemblyName>
    <Product>Unified UI Avalonia</Product>
    <Version>0.5.0</Version>
    <FileVersion>0.5.0.0</FileVersion>
    <InformationalVersion>0.5.0-final-nonqt</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.7" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.7" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.7" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.7" />
  </ItemGroup>
</Project>
